Python Version: 3.11.4


packages:
  - name: anyio
    version: 4.0.0
  - name: argon2-cffi
    version: 23.1.0
  - name: arrow
    version: 1.3.0
  - name: asttokens
    version: 2.4.1
  - name: async-lru
    version: 2.0.4
  - name: attrs
    version: 23.1.0
  - name: Babel
    version: 2.13.1
  - name: beautifulsoup4
    version: 4.12.2
  - name: bleach
    version: 6.1.0
  - name: Brotli
    version: 1.1.0
  - name: cached-property
    version: 1.5.2
  - name: certifi
    version: 2023.11.17
  - name: cffi
    version: 1.16.0
  - name: charset-normalizer
    version: 3.3.2
  - name: cloudpickle
    version: 3.0.0
  - name: colorama
    version: 0.4.6
  - name: comm
    version: 0.1.4
  - name: contourpy
    version: 1.2.0
  - name: cycler
    version: 0.12.1
  - name: debugpy
    version: 1.8.0
  - name: decorator
    version: 5.1.1
  - name: defusedxml
    version: 0.7.1
  - name: entrypoints
    version: 0.4
  - name: exceptiongroup
    version: 1.2.0
  - name: executing
    version: 2.0.1
  - name: fastjsonschema
    version: 2.19.0
  - name: fonttools
    version: 4.45.0
  - name: fqdn
    version: 1.5.1
  - name: idna
    version: 3.4
  - name: importlib-metadata
    version: 6.8.0
  - name: importlib-resources
    version: 6.1.1
  - name: ipykernel
    version: 6.26.0
  - name: ipython
    version: 8.17.2
  - name: ipywidgets
    version: 8.1.1
  - name: isoduration
    version: 20.11.0
  - name: jedi
    version: 0.19.1
  - name: Jinja2
    version: 3.1.2
  - name: joblib
    version: 1.3.2
  - name: json5
    version: 0.9.14
  - name: jsonpointer
    version: 2.4
  - name: jsonschema
    version: 4.20.0
  - name: jsonschema-specifications
    version: 2023.11.1
  - name: jupyter
    version: 1.0.0
  - name: jupyter_client
    version: 8.6.0
  - name: jupyter-console
    version: 6.6.3
  - name: jupyter_core
    version: 5.5.0
  - name: jupyter-events
    version: 0.9.0
  - name: jupyter-lsp
    version: 2.2.0
  - name: jupyter_server
    version: 2.11.0
  - name: jupyter_server_terminals
    version: 0.4.4
  - name: jupyterlab
    version: 4.0.9
  - name: jupyterlab-pygments
    version: 0.2.2
  - name: jupyterlab_server
    version: 2.25.2
  - name: jupyterlab-widgets
    version: 3.0.9
  - name: kiwisolver
    version: 1.4.5
  - name: llvmlite
    version: 0.41.1
  - name: MarkupSafe
    version: 2.1.3
  - name: matplotlib
    version: 3.7.2
  - name: matplotlib-inline
    version: 0.1.6
  - name: mistune
    version: 3.0.2
  - name: munkres
    version: 1.1.4
  - name: nbclient
    version: 0.8.0
  - name: nbconvert
    version: 7.11.0
  - name: nbformat
    version: 5.9.2
  - name: nest-asyncio
    version: 1.5.8
  - name: notebook
    version: 7.0.6
  - name: notebook_shim
    version: 0.2.3
  - name: numba
    version: 0.58.1
  - name: numpy
    version: 1.24.4
  - name: overrides
    version: 7.4.0
  - name: packaging
    version: 23.2
  - name: pandas
    version: 2.0.3
  - name: pandocfilters
    version: 1.5.0
  - name: parso
    version: 0.8.3
  - name: patsy
    version: 0.5.3
  - name: pickleshare
    version: 0.7.5
  - name: Pillow
    version: 10.0.1
  - name: pip
    version: 23.3.1
  - name: pkgutil_resolve_name
    version: 1.3.10
  - name: platformdirs
    version: 4.0.0
  - name: ply
    version: 3.11
  - name: prometheus-client
    version: 0.19.0
  - name: prompt-toolkit
    version: 3.0.41
  - name: psutil
    version: 5.9.5
  - name: pure-eval
    version: 0.2.2
  - name: pycparser
    version: 2.21
  - name: Pygments
    version: 2.17.1
  - name: pyparsing
    version: 3
